from models.schemas import ClauseResult, ResultsResponse, RiskAxes, RiskDistribution


def build_mock_results(session_id: str, document_name: str, page_count: int) -> ResultsResponse:
    clauses = [
        ClauseResult(
            id="clause_001",
            type="Indemnification",
            text="The vendor shall indemnify, defend, and hold harmless the customer from and against any and all claims, losses, liabilities, damages, penalties, and costs arising out of the services, without limitation as to amount or duration.",
            page_number=min(page_count, 2),
            bbox=(76, 112, 514, 178),
            risk_score=9.1,
            risk_axes=RiskAxes(liability=9, indemnity=10, ip_rights=3, termination=5),
            risk_level="critical",
            explanation="This clause creates an uncapped indemnity obligation that could expose the vendor to open-ended third-party claims and defense costs.",
            renegotiation_suggestion="Cap indemnity exposure to a negotiated multiple of annual fees and exclude indirect or unforeseeable losses.",
            similar_safe_clause="Vendor indemnity obligations will be limited to third-party IP infringement claims and capped at two times fees paid under this agreement.",
        ),
        ClauseResult(
            id="clause_002",
            type="Limitation of Liability",
            text="Except for customer payment obligations, vendor liability shall be unlimited and includes consequential, incidental, and punitive damages whether in contract, tort, or otherwise.",
            page_number=min(page_count, 2),
            bbox=(76, 214, 520, 270),
            risk_score=8.7,
            risk_axes=RiskAxes(liability=10, indemnity=7, ip_rights=2, termination=4),
            risk_level="critical",
            explanation="The clause removes the usual liability cap and expressly permits consequential damages, which materially expands financial exposure.",
            renegotiation_suggestion="Restore a mutual liability cap tied to fees paid and carve out only narrow exceptions such as fraud or intentional misconduct.",
            similar_safe_clause="Neither party's aggregate liability shall exceed the total fees paid in the twelve months preceding the claim, excluding fraud and willful misconduct.",
        ),
        ClauseResult(
            id="clause_003",
            type="Termination",
            text="Customer may terminate this agreement for convenience upon ten days' notice, and vendor must refund any prepaid fees on a pro rata basis.",
            page_number=min(page_count, 3),
            bbox=(70, 94, 505, 146),
            risk_score=7.6,
            risk_axes=RiskAxes(liability=5, indemnity=2, ip_rights=1, termination=9),
            risk_level="high",
            explanation="A unilateral convenience termination right with a short notice period weakens revenue predictability and gives the customer an easy exit.",
            renegotiation_suggestion="Require a longer notice period and make termination for convenience either mutual or subject to an early termination fee.",
            similar_safe_clause="Either party may terminate for convenience with sixty days' written notice after the initial twelve-month term.",
        ),
        ClauseResult(
            id="clause_004",
            type="IP Assignment",
            text="All deliverables, derivative works, tools, methods, and know-how developed or used in connection with the services shall be deemed works made for hire and owned exclusively by the customer.",
            page_number=min(page_count, 4),
            bbox=(74, 184, 510, 242),
            risk_score=8.1,
            risk_axes=RiskAxes(liability=4, indemnity=2, ip_rights=10, termination=3),
            risk_level="high",
            explanation="The ownership language is broad enough to sweep in pre-existing tools and general know-how, threatening the vendor's core intellectual property.",
            renegotiation_suggestion="Limit assignment to project-specific deliverables and expressly carve out pre-existing IP, templates, and generalized learnings.",
            similar_safe_clause="Customer will own final deliverables created exclusively for the project, while vendor retains all rights in pre-existing materials, tools, and know-how.",
        ),
        ClauseResult(
            id="clause_005",
            type="Governing Law",
            text="This agreement shall be governed by the laws of the State of New York, and the parties consent exclusively to venue in courts located in Manhattan, New York.",
            page_number=min(page_count, 4),
            bbox=(78, 286, 500, 334),
            risk_score=5.9,
            risk_axes=RiskAxes(liability=3, indemnity=2, ip_rights=1, termination=4),
            risk_level="medium",
            explanation="The governing law clause is common, but it may create litigation and travel burdens if the vendor operates elsewhere.",
            similar_safe_clause="The agreement will be governed by Delaware law, and the parties will first attempt to resolve disputes through remote mediation before litigation.",
        ),
        ClauseResult(
            id="clause_006",
            type="Non-Compete",
            text="Vendor shall not provide products or services substantially similar to the services for any competitor of customer during the term and for two years thereafter.",
            page_number=min(page_count, 5),
            bbox=(70, 104, 508, 162),
            risk_score=7.2,
            risk_axes=RiskAxes(liability=4, indemnity=1, ip_rights=5, termination=8),
            risk_level="high",
            explanation="The restraint is broad in scope and duration, which could materially limit the vendor's ability to serve adjacent customers.",
            renegotiation_suggestion="Narrow the restriction to named competitors, specific services, and a shorter post-term period if one is needed at all.",
            similar_safe_clause="Vendor will avoid direct solicitation of listed strategic accounts for six months following termination.",
        ),
        ClauseResult(
            id="clause_007",
            type="Confidentiality",
            text="Confidential information must be protected using at least reasonable care, and obligations will survive for three years after disclosure except for trade secrets, which survive as long as protected by law.",
            page_number=min(page_count, 5),
            bbox=(72, 216, 512, 270),
            risk_score=3.4,
            risk_axes=RiskAxes(liability=3, indemnity=1, ip_rights=4, termination=2),
            risk_level="low",
            explanation="This clause is balanced and follows standard confidentiality terms without unusual exposure.",
            similar_safe_clause="Each party will protect confidential information with reasonable care and limit access to personnel with a need to know.",
        ),
        ClauseResult(
            id="clause_008",
            type="Payment Terms",
            text="Invoices are due within fifteen days, and customer may withhold disputed amounts in good faith pending resolution of any claimed deficiency in services.",
            page_number=min(page_count, 6),
            bbox=(76, 112, 515, 168),
            risk_score=4.8,
            risk_axes=RiskAxes(liability=2, indemnity=1, ip_rights=1, termination=3),
            risk_level="medium",
            explanation="Fifteen-day payment terms are workable, but open-ended withholding rights can create collection friction.",
            similar_safe_clause="Undisputed amounts are due within thirty days, and disputed portions must be identified in writing with reasonable detail within ten business days.",
        ),
        ClauseResult(
            id="clause_009",
            type="Data Security",
            text="Vendor shall maintain industry-standard safeguards and notify customer of any confirmed security incident affecting customer data within seventy-two hours.",
            page_number=min(page_count, 6),
            bbox=(74, 196, 506, 248),
            risk_score=4.2,
            risk_axes=RiskAxes(liability=4, indemnity=2, ip_rights=1, termination=2),
            risk_level="low",
            explanation="The obligation is operationally meaningful but not unusually aggressive for modern SaaS or services agreements.",
            similar_safe_clause="Vendor will maintain commercially reasonable administrative, technical, and physical safeguards and notify customer without undue delay after confirming a breach.",
        ),
        ClauseResult(
            id="clause_010",
            type="Audit Rights",
            text="Customer may audit vendor's books, records, systems, and relevant subcontractor controls on ten days' notice up to four times per year at vendor's expense.",
            page_number=min(page_count, 7 if page_count >= 7 else page_count),
            bbox=(70, 286, 510, 346),
            risk_score=6.8,
            risk_axes=RiskAxes(liability=5, indemnity=1, ip_rights=2, termination=6),
            risk_level="medium",
            explanation="Frequent audit rights and vendor-borne costs can create operational overhead, especially if the scope reaches systems and subcontractors.",
            similar_safe_clause="Customer may conduct one audit annually on reasonable notice during business hours, subject to confidentiality and without disrupting operations.",
        ),
    ]

    distribution = RiskDistribution(
        critical=sum(clause.risk_level == "critical" for clause in clauses),
        high=sum(clause.risk_level == "high" for clause in clauses),
        medium=sum(clause.risk_level == "medium" for clause in clauses),
        low=sum(clause.risk_level == "low" for clause in clauses),
    )

    return ResultsResponse(
        session_id=session_id,
        document_name=document_name,
        total_clauses=len(clauses),
        overall_risk_score=74,
        processing_time_seconds=8.3,
        clauses=clauses,
        risk_distribution=distribution,
    )
